version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_ftt
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ftt_network

  app:
    build: .
    container_name: ftt_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/__pycache__
    networks:
      - ftt_network

networks:
  ftt_network:
    driver: bridge

volumes:
  postgres_data: